// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjJ_nbk5v_KKUuT100x2N18V-jNGxYhBg',
    appId: '1:589316337918:web:91e188cba7c9f0fba2b5af',
    messagingSenderId: '589316337918',
    projectId: 'project-n1-1f74e',
    authDomain: 'project-n1-1f74e.firebaseapp.com',
    storageBucket: 'project-n1-1f74e.appspot.com',
    measurementId: 'G-C1CZ8GVPQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-0CryTcXMSUguh7Tc8GHN8ch_Yt0i00I',
    appId: '1:589316337918:android:8bce4ebdddbb9f43a2b5af',
    messagingSenderId: '589316337918',
    projectId: 'project-n1-1f74e',
    storageBucket: 'project-n1-1f74e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMy2ua4pOSXWCUTSUhK_T5uOK90BXzjLg',
    appId: '1:589316337918:ios:564fb32827c53b9fa2b5af',
    messagingSenderId: '589316337918',
    projectId: 'project-n1-1f74e',
    storageBucket: 'project-n1-1f74e.appspot.com',
    iosClientId: '589316337918-bglhkog8enlub97vprtgvir84ha8e6o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectN1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMy2ua4pOSXWCUTSUhK_T5uOK90BXzjLg',
    appId: '1:589316337918:ios:564fb32827c53b9fa2b5af',
    messagingSenderId: '589316337918',
    projectId: 'project-n1-1f74e',
    storageBucket: 'project-n1-1f74e.appspot.com',
    iosClientId: '589316337918-bglhkog8enlub97vprtgvir84ha8e6o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectN1',
  );
}
